### ISSUE TITLE
Packaging latest version in nixpkgs: "error: illegal path references in fixed-output derivation"

### ISSUE THREAD

**Issue by bjornfor** [tiiuae/sbomnix#113] opened 2024-03-22 09:00 UTC
Hi,

I tried updating sbomnix (1.4.5 -> 1.6.0) in nixpkgs but hit this weird issue:

```
$ nix-build -A sbomnix
these 2 derivations will be built:
  /nix/store/g9zk3n7zhj4bgb22llns0y2kh2d89nr1-source.drv
  /nix/store/0y11vlrxgs9zlaxfv6dm6dkbclc0ml6h-sbomnix-1.6.0.drv
building '/nix/store/g9zk3n7zhj4bgb22llns0y2kh2d89nr1-source.drv'...

trying https://github.com/tiiuae/sbomnix/archive/refs/tags/v1.6.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  163k    0  163k    0     0   329k      0 --:--:-- --:--:-- --:--:--  329k
unpacking source archive /build/v1.6.0.tar.gz
error: illegal path references in fixed-output derivation '/nix/store/g9zk3n7zhj4bgb22llns0y2kh2d89nr1-source.drv'
error: 1 dependencies of derivation '/nix/store/0y11vlrxgs9zlaxfv6dm6dkbclc0ml6h-sbomnix-1.6.0.drv' failed to build
```

Not sure if this is an issue with Nix, nixpkgs or sbomnix, but thought I should start documenting the issue _somewhere_.

**Comment by joinemm** [comment] 2024-03-22 10:35
We are currently in the process of updating the nixpkgs version.

I ran into this same issue when using the wrong sha256 hash, or `lib.fakeHash`. Updating the hash to one I got from running `nix flake prefetch github:tiiuae/sbomnix/refs/tags/v1.6.0` makes the build actually start.

But there are some new python dependencies added to sbomnix, that are not specified in the derivation. Most of these are available in nixpkgs so they are trivial to add, but `dfdiskcache` is not packaged in nixpkgs unfortunately.

**Comment by henrirosten** [comment] 2024-03-27 07:38
I see this same problem, and I also don't fully understand why this happens. Nixpkgs sbomnix update draft PR for reference: https://github.com/NixOS/nixpkgs/pull/299429.

**Comment by henrirosten** [comment] 2024-03-28 13:29
I think the problem is fixed with: https://github.com/NixOS/nixpkgs/pull/299429/commits/68cc92f58bb643f2bfa4a13cc3bd0b82c8034aac

The commit message tries to explain the root-cause:

```
Apparently nix does not like '/nix/store/...' references in the source
tarball. Sbomnix documentation includes a number of store references.
Since documentation is part of the sbmonix tarball as downloaded from
github, we need to remove all documentation files from inside the
tarball that might have '/nix/store' references in them. This commit
adds a `postFetch` phase to the sbomnix build to do just that.
```

**Comment by bjornfor** [comment] 2024-03-28 13:51
How about using nukeReferences instead?

**Comment by henrirosten** [comment] 2024-03-28 14:20
I wasn't aware such script exists. How would you call it in this case to target everything under `doc` and all `.md` files also oustide `doc`?

**Comment by bjornfor** [comment] 2024-03-28 19:06
I'm not at a PC now, so I don't know/remember exactly how the tool works, but either it recurses itself from a starting path or you have to use "find" and explicitly give all paths to it.

**Comment by henrirosten** [comment] 2024-04-02 07:46
Tried with something like:

```
python.pkgs.buildPythonApplication rec {
  pname = "sbomnix";
  version = "1.6.1";

  src = fetchFromGitHub {
    owner = "tiiuae";
    repo = "sbomnix";
    rev = "refs/tags/v${version}";
    hash = "";

    # Remove documentation as it contains references to nix store
    postFetch = ''
      find "$out" -type f \( -name '*.md' -o -name '*.svg' \) -exec echo '{}' \; -exec ${nukeReferences}/bin/nuke-refs '{}' \;
    '';
  };
  ```
  It runs but clearly the store reference replace fails somewhere as the build still fails. I opted [using `rm` instead](https://github.com/NixOS/nixpkgs/blob/3141a79e802dca5cf5acf9b8245d5b930b83733a/pkgs/tools/security/sbomnix/default.nix#L49-L52) which seems way simpler in this case.

**Comment by henrirosten** [comment] 2024-04-09 13:09
Closing this issue as the [nixpkgs PR](https://github.com/NixOS/nixpkgs/pull/299429) got merged.

**Closed** 2024-04-09 13:09 UTC

**Comment by bjornfor** [comment] 2024-04-29 07:40
Related: https://discourse.nixos.org/t/illegal-path-references-in-fixed-output-derivation/44360
